2023-05-22 14:16:45,317 ERROR: Exception on /translate [POST] [in e:\software\miniconda\envs\web\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "e:\software\miniconda\envs\web\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "E:\Coding\microblog\app\routes.py", line 216, in translate_text
    request.form['dest_language'])})
  File "E:\Coding\microblog\app\translate.py", line 27, in translate
    dest_language = get_dest_language(dest_language)
NameError: name 'get_dest_language' is not defined
2023-05-22 14:17:04,653 ERROR: Exception on /translate [POST] [in e:\software\miniconda\envs\web\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "e:\software\miniconda\envs\web\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "E:\Coding\microblog\app\routes.py", line 216, in translate_text
    request.form['dest_language'])})
  File "E:\Coding\microblog\app\translate.py", line 27, in translate
    dest_language = get_dest_language(dest_language)
NameError: name 'get_dest_language' is not defined
2023-05-22 14:17:39,386 INFO: Microblog startup [in E:\Coding\microblog\app\__init__.py:52]
2023-05-22 14:19:19,212 INFO: Microblog startup [in E:\Coding\microblog\app\__init__.py:52]
2023-05-22 14:21:32,448 INFO: Microblog startup [in E:\Coding\microblog\app\__init__.py:52]
2023-05-22 14:21:59,308 INFO: Microblog startup [in E:\Coding\microblog\app\__init__.py:52]
2023-05-22 14:22:04,425 INFO: Microblog startup [in E:\Coding\microblog\app\__init__.py:52]
2023-05-22 14:58:28,592 INFO: Microblog startup [in E:\Coding\microblog\app\__init__.py:52]
2023-05-22 14:58:35,619 INFO: Microblog startup [in E:\Coding\microblog\app\__init__.py:52]
2023-05-22 15:03:44,285 INFO: Microblog startup [in E:\Coding\microblog\app\__init__.py:52]
2023-05-22 15:03:52,910 ERROR: Exception on /translate [POST] [in e:\software\miniconda\envs\web\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "e:\software\miniconda\envs\web\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "E:\Coding\microblog\app\routes.py", line 216, in translate_text
    request.form['dest_language'])})
  File "E:\Coding\microblog\app\translate.py", line 27, in translate
    dest_language = get_language_code(dest_language)
  File "E:\Coding\microblog\app\translate.py", line 17, in get_language_code
    return language_codes[lang]
KeyError: 'zh_Hans_CN'
2023-05-22 15:04:30,740 INFO: Microblog startup [in E:\Coding\microblog\app\__init__.py:52]
2023-05-22 15:04:54,283 INFO: Microblog startup [in E:\Coding\microblog\app\__init__.py:52]
2023-05-22 15:06:36,746 INFO: Microblog startup [in E:\Coding\microblog\app\__init__.py:52]
2023-05-22 15:06:46,531 ERROR: Exception on /translate [POST] [in e:\software\miniconda\envs\web\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "e:\software\miniconda\envs\web\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "E:\Coding\microblog\app\routes.py", line 216, in translate_text
    request.form['dest_language'])})
  File "E:\Coding\microblog\app\translate.py", line 27, in translate
    dest_language = get_language_code(dest_language)
  File "E:\Coding\microblog\app\translate.py", line 17, in get_language_code
    return language_codes[lang]
KeyError: 'zh'
2023-05-22 15:10:08,146 INFO: Microblog startup [in E:\Coding\microblog\app\__init__.py:52]
2023-05-22 15:10:15,138 ERROR: Exception on /translate [POST] [in e:\software\miniconda\envs\web\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "e:\software\miniconda\envs\web\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "E:\Coding\microblog\app\routes.py", line 216, in translate_text
    request.form['dest_language'])})
  File "E:\Coding\microblog\app\translate.py", line 27, in translate
    dest_language = get_language_code(dest_language)
  File "E:\Coding\microblog\app\translate.py", line 17, in get_language_code
    return language_codes[lang]
KeyError: 'zh_Hans_CN'
2023-05-22 15:12:04,243 INFO: Microblog startup [in E:\Coding\microblog\app\__init__.py:52]
