2023-05-22 15:26:36,489 ERROR: Exception on /translate [POST] [in e:\software\miniconda\envs\web\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "e:\software\miniconda\envs\web\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "E:\Coding\microblog\app\routes.py", line 216, in translate_text
    request.form['dest_language'])})
  File "E:\Coding\microblog\app\translate.py", line 27, in translate
    dest_language = get_language_code(dest_language)
  File "E:\Coding\microblog\app\translate.py", line 17, in get_language_code
    return language_codes[lang]
KeyError: 'zh_Hans_CN'
2023-05-22 15:28:16,809 INFO: Microblog startup [in E:\Coding\microblog\app\__init__.py:52]
2023-05-22 15:28:21,437 ERROR: Exception on /translate [POST] [in e:\software\miniconda\envs\web\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "e:\software\miniconda\envs\web\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "E:\Coding\microblog\app\routes.py", line 217, in translate_text
    request.form['dest_language'])})
  File "E:\Coding\microblog\app\translate.py", line 27, in translate
    dest_language = get_language_code(dest_language)
  File "E:\Coding\microblog\app\translate.py", line 17, in get_language_code
    return language_codes[lang]
KeyError: 'zh_Hans_CN'
2023-05-22 15:32:42,526 INFO: Microblog startup [in E:\Coding\microblog\app\__init__.py:52]
2023-05-22 15:33:01,224 INFO: Microblog startup [in E:\Coding\microblog\app\__init__.py:52]
2023-05-22 15:33:25,428 INFO: Microblog startup [in E:\Coding\microblog\app\__init__.py:52]
2023-05-22 15:33:57,617 INFO: Microblog startup [in E:\Coding\microblog\app\__init__.py:52]
2023-05-22 15:35:56,291 INFO: Microblog startup [in E:\Coding\microblog\app\__init__.py:52]
2023-05-22 15:36:02,505 INFO: Microblog startup [in E:\Coding\microblog\app\__init__.py:52]
2023-05-22 15:36:34,906 INFO: Microblog startup [in E:\Coding\microblog\app\__init__.py:52]
2023-05-22 15:37:51,510 INFO: Microblog startup [in E:\Coding\microblog\app\__init__.py:52]
2023-05-22 15:38:07,462 INFO: Microblog startup [in E:\Coding\microblog\app\__init__.py:52]
2023-05-22 15:42:31,090 INFO: Microblog startup [in E:\Coding\microblog\app\__init__.py:52]
2023-05-22 15:44:36,934 INFO: Microblog startup [in E:\Coding\microblog\app\__init__.py:52]
2023-05-22 15:48:22,474 INFO: Microblog startup [in E:\Coding\microblog\app\__init__.py:52]
2023-05-22 15:49:01,458 INFO: Microblog startup [in E:\Coding\microblog\app\__init__.py:52]
2023-05-22 15:49:59,144 INFO: Microblog startup [in E:\Coding\microblog\app\__init__.py:52]
2023-05-22 15:50:20,653 INFO: Microblog startup [in E:\Coding\microblog\app\__init__.py:52]
2023-05-22 15:59:40,237 INFO: Microblog startup [in E:\Coding\microblog\app\__init__.py:52]
2023-05-22 15:59:46,967 ERROR: Exception on /index [GET] [in e:\software\miniconda\envs\web\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1948, in full_dispatch_request
    rv = self.preprocess_request()
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 2242, in preprocess_request
    rv = func()
  File "E:\Coding\microblog\app\routes.py", line 21, in before_request
    g.locale = str(get_locale())
  File "e:\software\miniconda\envs\web\lib\site-packages\flask_babel\__init__.py", line 230, in get_locale
    locale = Locale.parse(rv)
  File "e:\software\miniconda\envs\web\lib\site-packages\babel\core.py", line 268, in parse
    parts = parse_locale(identifier, sep=sep)
  File "e:\software\miniconda\envs\web\lib\site-packages\babel\core.py", line 1094, in parse_locale
    raise ValueError('expected only letters, got %r' % lang)
ValueError: expected only letters, got 'zh-cn'
2023-05-22 16:00:53,531 INFO: Microblog startup [in E:\Coding\microblog\app\__init__.py:52]
2023-05-22 16:00:59,874 ERROR: Exception on /translate [POST] [in e:\software\miniconda\envs\web\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "e:\software\miniconda\envs\web\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "E:\Coding\microblog\app\routes.py", line 216, in translate_text
    request.form['dest_language'])})
  File "E:\Coding\microblog\app\translate.py", line 27, in translate
    dest_language = get_language_code(dest_language)
  File "E:\Coding\microblog\app\translate.py", line 17, in get_language_code
    return language_codes[lang]
KeyError: 'zh'
2023-05-22 16:01:25,071 INFO: Microblog startup [in E:\Coding\microblog\app\__init__.py:52]
2023-05-22 16:01:43,425 INFO: Microblog startup [in E:\Coding\microblog\app\__init__.py:52]
2023-05-22 16:02:11,938 INFO: Microblog startup [in E:\Coding\microblog\app\__init__.py:52]
2023-05-22 16:05:08,891 INFO: Microblog startup [in E:\Coding\microblog\app\__init__.py:52]
2023-05-22 16:09:55,285 INFO: Microblog startup [in E:\Coding\microblog\app\__init__.py:52]
2023-05-22 16:10:23,784 INFO: Microblog startup [in E:\Coding\microblog\app\__init__.py:52]
2023-05-22 16:10:55,083 INFO: Microblog startup [in E:\Coding\microblog\app\__init__.py:52]
2023-05-22 16:11:03,680 INFO: Microblog startup [in E:\Coding\microblog\app\__init__.py:52]
2023-05-22 16:11:07,403 ERROR: Exception on /translate [POST] [in e:\software\miniconda\envs\web\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "e:\software\miniconda\envs\web\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "E:\Coding\microblog\app\routes.py", line 217, in translate_text
    request.form['dest_language'])})
  File "E:\Coding\microblog\app\translate.py", line 27, in translate
    dest_language = get_language_code(dest_language)
  File "E:\Coding\microblog\app\translate.py", line 17, in get_language_code
    return language_codes[lang]
KeyError: 'zh'
