2023-05-22 15:12:07,851 ERROR: Exception on /translate [POST] [in e:\software\miniconda\envs\web\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "e:\software\miniconda\envs\web\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "E:\Coding\microblog\app\routes.py", line 216, in translate_text
    request.form['dest_language'])})
  File "E:\Coding\microblog\app\translate.py", line 27, in translate
    dest_language = get_language_code(dest_language)
  File "E:\Coding\microblog\app\translate.py", line 17, in get_language_code
    return language_codes[lang]
KeyError: 'zh_Hans_CN'
2023-05-22 15:14:09,357 INFO: Microblog startup [in E:\Coding\microblog\app\__init__.py:52]
2023-05-22 15:14:13,157 ERROR: Exception on /translate [POST] [in e:\software\miniconda\envs\web\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "e:\software\miniconda\envs\web\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "E:\Coding\microblog\app\routes.py", line 216, in translate_text
    request.form['dest_language'])})
  File "E:\Coding\microblog\app\translate.py", line 27, in translate
    dest_language = get_language_code(dest_language)
  File "E:\Coding\microblog\app\translate.py", line 17, in get_language_code
    return language_codes[lang]
KeyError: 'zh_Hans_CN'
2023-05-22 15:16:09,140 INFO: Microblog startup [in E:\Coding\microblog\app\__init__.py:52]
2023-05-22 15:16:23,396 ERROR: Exception on /translate [POST] [in e:\software\miniconda\envs\web\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "e:\software\miniconda\envs\web\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "E:\Coding\microblog\app\routes.py", line 216, in translate_text
    request.form['dest_language'])})
  File "E:\Coding\microblog\app\translate.py", line 27, in translate
    dest_language = get_language_code(dest_language)
  File "E:\Coding\microblog\app\translate.py", line 17, in get_language_code
    return language_codes[lang]
KeyError: 'zh_Hans_CN'
2023-05-22 15:17:22,304 INFO: Microblog startup [in E:\Coding\microblog\app\__init__.py:52]
2023-05-22 15:17:24,960 ERROR: Exception on /translate [POST] [in e:\software\miniconda\envs\web\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "e:\software\miniconda\envs\web\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "E:\Coding\microblog\app\routes.py", line 217, in translate_text
    request.form['dest_language'])})
  File "E:\Coding\microblog\app\translate.py", line 27, in translate
    dest_language = get_language_code(dest_language)
  File "E:\Coding\microblog\app\translate.py", line 17, in get_language_code
    return language_codes[lang]
KeyError: 'zh_Hans_CN'
2023-05-22 15:17:46,053 INFO: Microblog startup [in E:\Coding\microblog\app\__init__.py:52]
2023-05-22 15:17:53,845 ERROR: Exception on /translate [POST] [in e:\software\miniconda\envs\web\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "e:\software\miniconda\envs\web\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "E:\Coding\microblog\app\routes.py", line 217, in translate_text
    request.form['dest_language'])})
  File "E:\Coding\microblog\app\translate.py", line 27, in translate
    dest_language = get_language_code(dest_language)
  File "E:\Coding\microblog\app\translate.py", line 17, in get_language_code
    return language_codes[lang]
KeyError: 'zh_Hans_CN'
2023-05-22 15:20:24,663 ERROR: Exception on /translate [POST] [in e:\software\miniconda\envs\web\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\software\miniconda\envs\web\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "e:\software\miniconda\envs\web\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "E:\Coding\microblog\app\routes.py", line 217, in translate_text
  File "E:\Coding\microblog\app\translate.py", line 27, in translate
    dest_language = get_language_code(dest_language)
  File "E:\Coding\microblog\app\translate.py", line 17, in get_language_code
    return language_codes[lang]
KeyError: 'zh_Hans_CN'
2023-05-22 15:26:31,813 INFO: Microblog startup [in E:\Coding\microblog\app\__init__.py:52]
